### ISSUE TITLE
Extract selection to new note - content only: More info for the user

### ISSUE THREAD

**Issue by mafsi** [lynchjames/note-refactor-obsidian#14]
### Steps to reproduce

1. Do the settings in Note Refactor: _Toggle OFF Include First line_

2. Select a paragraph:
```Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci. Aenean nec lorem.```

3. Trigger Key: Ctrl+Shift+C

4. Name the note: whatever
5. Hit Enter. (btw: hitting Enter is not working. We have to use mouse)

### Expected result
In user defined directory should be a note named: `whatever` and have the paragraph above as a content.

### Actual result
In user defined directory is a note named: `whatever` but with no content. Plugin doesn't consider a paragraph a single line.

### Environment

Windows 10
Obsidian: 0.9.10
----------

### Additional information

If I rewrite the paragraph in this way:

```Lorem ipsum dolor sit amet, consectetuer adipiscing elit.```
```Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci. Aenean nec lorem.```

I get the content but without the first line `Lorem ipsum dolor sit amet, consectetuer adipiscing elit.`. So, to include the first line I have to _Toggle ON Include First line_. This also work with paragraph from **Steps to reproduce**

**Is very confusing switching those toggles.** I suggest more explanation either in Readme file or in description of toggle inside the Note Refactor palette in Obsidian line: _If  toggle is OFF you will not get content extracted to a new note, if content is a paragraph. You need to have 2 lines of content and the content will be extracted WITHOUT first line. **If you want to select just one paragraph and want just to have the content you selected to be included in a new note ToggleON the button**._

Sorry for the long explanation. I hope I was a little bit cleared.

**Comment by DutchPete** [comment]
This is similar to my issue #7.

**Comment by mafsi** [comment]
Sorry for duplicate!

**Comment by lynchjames** [comment]
I can see the issue. I’m trying to provide flexibility with a different combinations of the commands and settings to cater for different usage (see #12 for example) but this can definitely lead to confusing behaviour. 

I think I’ll do the following:

1. Invert the setting to be exclude the first line from the note and have that setting only apply for the first line as filename commands. It doesn’t make sense to ever exclude the first line when using the content only commands because the first line is not used for anything else in these cases.  
1. Add more explanation in settings description about what they mean. 
1. Add a usage table in README to list different use cases with which command and settings to use for each. 

I’ll raise a separate issue for submitting the filename modal when hitting enter.

**Comment by DutchPete** [comment]
@mafsi It is not a duplicate, it is a similar issue 😉 It is good you submitted it because it shows the issue is not limited to me.

@lynchjames: those 3 points don't address the non-excision of the content from source note to new note.

**Comment by lynchjames** [comment]
@DutchPete ah so you’re still having that issue. Let’s pick that up in #7.
