### ISSUE TITLE
It would be nice to have an option for linking the new note inline

### ISSUE THREAD

**Issue by timothyjlaurent** [lynchjames/note-refactor-obsidian#20]
It would be nice if we could get inline links created, so that the derivative note would still display in the original note.

```
![[NEW Note name]]
```

**Comment by timothyjlaurent** [comment]
Forgot to mention -- Thanks for this!!

**Comment by lynchjames** [comment]
Thanks for the suggestion.

Interesting idea of replacing the content in place with an embed of that content in another file. There are a few ways to do this. Were you thinking of a config setting to always embed extracted and/or split notes or would you want a separate command for this?

There are already 4 separate commands used by this plugin so I'm a little reluctant to introduce more! However, that might be the right option if you (and others) think that embedding of linked extracted/split would be useful to have but depending on the context rather than as standard practice. The latter would lend itself more to a config setting.

**Comment by timothyjlaurent** [comment]
I think it would be nice to be able to go back and forth seamlessly. Maybe `CMD/CTL + ALT + SHIFT` does an embed. That would be sweet and idiomatic

**Comment by lynchjames** [comment]
Back and forth between (1) internal link and (2) embed/transclusion or back and forth between (1) splitting/extract a note into a derivative note and (2) merging that derivative note back into the original note? The latter is similar to the request for merging in #21 and would have similar challenges.

**Comment by lynchjames** [comment]
Option to transclude links to new notes by default has been added in [1.4.7](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.4.7).

Reverting the process to merge the note back into the original note will be covered under #21.

**Comment by timothyjlaurent** [comment]
This is awesome, thanks!
