### ISSUE TITLE
Extend functionality to split based on headings

### ISSUE THREAD

**Issue by dxcore35** [lynchjames/note-refactor-obsidian#22]
If you can replicate my function: https://github.com/dxcore35/obs-md-header-spliter

& make it as command in QUICK MENU >
- Split into individual files (based on H1 level)
- Split into individual files (based on H2 level)
- Split into individual files (based on H3 level)

It will be amazing!

**Comment by lynchjames** [comment]
This could be done with separate commands but I would prefer to introduce a single command that would be contextual based on the level of heading on the line of the cursor when the command is executed.

For example, if you wanted to split a note at H2 level, you would place the cursor on the line of one of the H2 headings and then run the command.

Would this be acceptable?

I'm assuming this would infer the name of the note from each of the headings at the selected level, is that what you were thinking? Otherwise, a multi-step or multi-input modal would be required for the user to enter the new note names.

**Comment by dxcore35** [comment]
Just check the repo, it is explained what is it doing.
Not sure if the cursor option is good one.

There is no other formatting then headings one what to split the file (let say book) into separated files. Each having name of the file from the heading that was splitted.

What you can do it just give extra options to  QUICK MENU >

Split into individual files (based on H1 level)
Split into individual files (based on H2 level)
Split into individual files (based on H3 level)

I doubt anybody need to split it in level 4 and lower....

What you can do afterward is link the splited files back to original files where you started the spliting as Obsidian ![[Link]]. This will be black magic :)

**Comment by lynchjames** [comment]
I have introduced these as separate plugin commands for H1, H2 and H3 because the quick menu doesn't have keyboard input focus at the moment.

Commands available in [1.5.1](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.5.1).
